package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * Airlines generated by hbm2java
 */

@Entity
@Table(name="Airlines")
public class Airlines implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="name")
	private String name;
	
	@Column(name="email")
	private String email;
	
	@Column(name="password")
	private byte[] password;
	
	@Column(name="salt")
	private byte[] salt;

	private Set routeses = new HashSet(0);
	private Set planeses = new HashSet(0);

	public Airlines() {
	}

	public Airlines(int id) {
		this.id = id;
	}

	public Airlines(int id, String name, String email, byte[] password, byte[] salt, Set routeses, Set planeses) {
		this.id = id;
		this.name = name;
		this.email = email;
		this.password = password;
		this.salt = salt;
		this.routeses = routeses;
		this.planeses = planeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public byte[] getPassword() {
		return this.password;
	}

	public void setPassword(byte[] password) {
		this.password = password;
	}

	public byte[] getSalt() {
		return this.salt;
	}

	public void setSalt(byte[] salt) {
		this.salt = salt;
	}

	public Set getRouteses() {
		return this.routeses;
	}

	public void setRouteses(Set routeses) {
		this.routeses = routeses;
	}

	public Set getPlaneses() {
		return this.planeses;
	}

	public void setPlaneses(Set planeses) {
		this.planeses = planeses;
	}

}
