package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Flights generated by hbm2java
 */

@Entity
@Table(name="Flights")
public class Flights implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="baggages")
	private Baggages baggages;
	
	@Column(name="gates")
	private Gates gates;
	
	@Column(name="planes")
	private Planes planes;
	
	@Column(name="routes")
	private Routes routes;
	
	@Column(name="duration")
	private Integer duration;
	
	@Column(name="delay")
	private Integer delay;
	
	@Column(name="dateDeparture")
	private Date dateDeparture;
	
	@Column(name="dateArrival")
	private Date dateArrival;
	
	private Set ticketses = new HashSet(0);

	public Flights() {
	}

	public Flights(int id, Baggages baggages, Gates gates, Planes planes, Routes routes) {
		this.id = id;
		this.baggages = baggages;
		this.gates = gates;
		this.planes = planes;
		this.routes = routes;
	}

	public Flights(int id, Baggages baggages, Gates gates, Planes planes, Routes routes, Integer duration,
			Integer delay, Date dateDeparture, Date dateArrival, Set ticketses) {
		this.id = id;
		this.baggages = baggages;
		this.gates = gates;
		this.planes = planes;
		this.routes = routes;
		this.duration = duration;
		this.delay = delay;
		this.dateDeparture = dateDeparture;
		this.dateArrival = dateArrival;
		this.ticketses = ticketses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Baggages getBaggages() {
		return this.baggages;
	}

	public void setBaggages(Baggages baggages) {
		this.baggages = baggages;
	}

	public Gates getGates() {
		return this.gates;
	}

	public void setGates(Gates gates) {
		this.gates = gates;
	}

	public Planes getPlanes() {
		return this.planes;
	}

	public void setPlanes(Planes planes) {
		this.planes = planes;
	}

	public Routes getRoutes() {
		return this.routes;
	}

	public void setRoutes(Routes routes) {
		this.routes = routes;
	}

	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Integer getDelay() {
		return this.delay;
	}

	public void setDelay(Integer delay) {
		this.delay = delay;
	}

	public Date getDateDeparture() {
		return this.dateDeparture;
	}

	public void setDateDeparture(Date dateDeparture) {
		this.dateDeparture = dateDeparture;
	}

	public Date getDateArrival() {
		return this.dateArrival;
	}

	public void setDateArrival(Date dateArrival) {
		this.dateArrival = dateArrival;
	}

	public Set getTicketses() {
		return this.ticketses;
	}

	public void setTicketses(Set ticketses) {
		this.ticketses = ticketses;
	}

}
