package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Flights generated by hbm2java
 */

@Entity
@Table(name="Flights")
public class Flights implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static Date d_Departure = new Date();
	private static Date d_Time = new Date();
	
	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="baggage_id")
	private int baggage_id;
	
	@Column(name="gate_id")
	private int gate_id;
	
	@Column(name="plane_id")
	private int plane_id;
	
	@Column(name="route_id")
	private int route_id;
	
	@Column(name="duration")
	private Date duration;
	
	@Column(name="delay")
	private Date delay;
	
	@Column(name="date_departure")
	private Date dateDeparture;
	


	public Flights() {
	}

	public Flights(int id, int baggages, int gates, int planes, int routes) {
		this.id = id;
		this.baggage_id = baggages;
		this.gate_id = gates;
		this.plane_id = planes;
		this.route_id = routes;
	}

	public Flights(int id, int baggages, int gates, int planes, int routes, Date duration,
			Date delay, Date dateDeparture) {
		this.id = id;
		this.baggage_id = baggages;
		this.gate_id = gates;
		this.plane_id = planes;
		this.route_id = routes;
		this.duration = duration;
		this.delay = delay;
		this.dateDeparture = dateDeparture;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getBaggage_id() {
		return baggage_id;
	}

	public void setBaggage_id(int baggage_id) {
		this.baggage_id = baggage_id;
	}

	public int getGate_id() {
		return gate_id;
	}

	public void setGate_id(int gate_id) {
		this.gate_id = gate_id;
	}

	public int getPlane_id() {
		return plane_id;
	}

	public void setPlane_id(int plane_id) {
		this.plane_id = plane_id;
	}

	public int getRoute_id() {
		return route_id;
	}

	public void setRoute_id(int route_id) {
		this.route_id = route_id;
	}

	public Date getDuration() {
		return this.duration;
	}

	public void setDuration(Date duration) {
		this.duration = duration;
	}

	public Date getDelay() {
		return this.delay;
	}

	public void setDelay(Date delay) {
		this.delay = delay;
	}

	public Date getDateDeparture() {
		return this.dateDeparture;
	}

	public void setDateDeparture(Date dateDeparture) {
		this.dateDeparture = dateDeparture;
	}
	
	@SuppressWarnings("deprecation")
	public Date getDatePlus(){
		long sum = d_Departure.getTime() + d_Time.getHours() + d_Time.getMinutes() + d_Time.getSeconds();
		return new Date(sum);
	}
}
