package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlaneStatus generated by hbm2java
 */

@Entity
@Table(name="PlaneStatus")
public class PlaneStatus implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="name")
	private String name;
	
	private Set planeses = new HashSet(0);

	public PlaneStatus() {
	}

	public PlaneStatus(int id) {
		this.id = id;
	}

	public PlaneStatus(int id, String name, Set planeses) {
		this.id = id;
		this.name = name;
		this.planeses = planeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getPlaneses() {
		return this.planeses;
	}

	public void setPlaneses(Set planeses) {
		this.planeses = planeses;
	}

}
