package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlaneMovements generated by hbm2java
 */

@Entity
@Table(name="PlaneMovements")
public class PlaneMovements implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="planes")
	private Planes planes;
	
	@Column(name="posx")
	private Integer posx;
	
	@Column(name="posy")
	private Integer posy;
	
	@Column(name="dirx")
	private Integer dirx;
	
	@Column(name="diry")
	private Integer diry;

	public PlaneMovements() {
	}

	public PlaneMovements(int id, Planes planes) {
		this.id = id;
		this.planes = planes;
	}

	public PlaneMovements(int id, Planes planes, Integer posx, Integer posy, Integer dirx, Integer diry) {
		this.id = id;
		this.planes = planes;
		this.posx = posx;
		this.posy = posy;
		this.dirx = dirx;
		this.diry = diry;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Planes getPlanes() {
		return this.planes;
	}

	public void setPlanes(Planes planes) {
		this.planes = planes;
	}

	public Integer getPosx() {
		return this.posx;
	}

	public void setPosx(Integer posx) {
		this.posx = posx;
	}

	public Integer getPosy() {
		return this.posy;
	}

	public void setPosy(Integer posy) {
		this.posy = posy;
	}

	public Integer getDirx() {
		return this.dirx;
	}

	public void setDirx(Integer dirx) {
		this.dirx = dirx;
	}

	public Integer getDiry() {
		return this.diry;
	}

	public void setDiry(Integer diry) {
		this.diry = diry;
	}

}
