/*
 * 
 */
package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * Planes generated by hbm2java.
 */

@Entity
@Table(name="Planes")
public class Planes implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The number hours. */
	@Transient
	private String numberHours;
	
	/** The number flights. */
	@Transient 
	private int numberFlights;
	
	/** The plane name. */
	@Transient
	private String plane_name;
	
	/** The id. */
	@Id
	@Column(name="id")
	private int id;
	
	/** The airline id. */
	@Column(name="Airline_id")
	private int airline_id;
	
	/** The plane model id. */
	@Column(name="Plane_Model_id")
	private int planeModel_id;
	
	/** The plane statu id. */
	@Column(name="Plane_Status_id")
	private int planeStatu_id;

	/**
	 * Instantiates a new planes.
	 */
	public Planes() {
	}

	/**
	 * Instantiates a new planes.
	 *
	 * @param id the id
	 * @param airlines the airlines
	 * @param planeModels the plane models
	 * @param planeStatus the plane status
	 */
	public Planes(int id, int airlines, int planeModels, int planeStatus) {
		this.id = id;
		this.airline_id = airlines;
		this.planeModel_id = planeModels;
		this.planeStatu_id = planeStatus;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the airline id.
	 *
	 * @return the airline id
	 */
	public int getAirline_id() {
		return airline_id;
	}

	/**
	 * Sets the airline id.
	 *
	 * @param airline_id the new airline id
	 */
	public void setAirline_id(int airline_id) {
		this.airline_id = airline_id;
	}

	/**
	 * Gets the plane model id.
	 *
	 * @return the plane model id
	 */
	public int getPlaneModel_id() {
		return planeModel_id;
	}

	/**
	 * Sets the plane model id.
	 *
	 * @param planeModel_id the new plane model id
	 */
	public void setPlaneModel_id(int planeModel_id) {
		this.planeModel_id = planeModel_id;
	}

	/**
	 * Gets the plane statu id.
	 *
	 * @return the plane statu id
	 */
	public int getPlaneStatu_id() {
		return planeStatu_id;
	}

	/**
	 * Sets the plane statu id.
	 *
	 * @param planeStatu_id the new plane statu id
	 */
	public void setPlaneStatu_id(int planeStatu_id) {
		this.planeStatu_id = planeStatu_id;
	}

	/**
	 * Gets the number hours.
	 *
	 * @return the number hours
	 */
	public String getNumberHours() {
		return numberHours;
	}

	/**
	 * Sets the number hours.
	 *
	 * @param numberHours the new number hours
	 */
	public void setNumberHours(String numberHours) {
		this.numberHours = numberHours;
	}

	/**
	 * Gets the number flights.
	 *
	 * @return the number flights
	 */
	public int getNumberFlights() {
		return numberFlights;
	}

	/**
	 * Sets the number flights.
	 *
	 * @param numberFlights the new number flights
	 */
	public void setNumberFlights(int numberFlights) {
		this.numberFlights = numberFlights;
	}

	/**
	 * Gets the plane name.
	 *
	 * @return the plane name
	 */
	public String getPlane_name() {
		return plane_name;
	}

	/**
	 * Sets the plane name.
	 *
	 * @param plane_name the new plane name
	 */
	public void setPlane_name(String plane_name) {
		this.plane_name = plane_name;
	}
	
	
	
}
