package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PlaneModels generated by hbm2java
 */

@Entity
@Table(name="PlaneModels")
public class PlaneModels implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="Manufacturers")
	private Manufacturers manufacturers;
	
	@Column(name="name")
	private String name;
	
	@Column(name="maxPassengers")
	private Integer maxPassengers;
	
	private Set planeses = new HashSet(0);

	public PlaneModels() {
	}

	public PlaneModels(int id, Manufacturers manufacturers) {
		this.id = id;
		this.manufacturers = manufacturers;
	}

	public PlaneModels(int id, Manufacturers manufacturers, String name, Integer maxPassengers, Set planeses) {
		this.id = id;
		this.manufacturers = manufacturers;
		this.name = name;
		this.maxPassengers = maxPassengers;
		this.planeses = planeses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Manufacturers getManufacturers() {
		return this.manufacturers;
	}

	public void setManufacturers(Manufacturers manufacturers) {
		this.manufacturers = manufacturers;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getMaxPassengers() {
		return this.maxPassengers;
	}

	public void setMaxPassengers(Integer maxPassengers) {
		this.maxPassengers = maxPassengers;
	}

	public Set getPlaneses() {
		return this.planeses;
	}

	public void setPlaneses(Set planeses) {
		this.planeses = planeses;
	}

}
