package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Planes generated by hbm2java
 */

@Entity
@Table(name="Planes")
public class Planes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="airlines")
	private Airlines airlines;
	
	@Column(name="planeModels")
	private PlaneModels planeModels;
	
	@Column(name="planeStatus")
	private PlaneStatus planeStatus;

	public Planes() {
	}

	public Planes(int id, Airlines airlines, PlaneModels planeModels, PlaneStatus planeStatus) {
		this.id = id;
		this.airlines = airlines;
		this.planeModels = planeModels;
		this.planeStatus = planeStatus;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Airlines getAirlines() {
		return this.airlines;
	}

	public void setAirlines(Airlines airlines) {
		this.airlines = airlines;
	}

	public PlaneModels getPlaneModels() {
		return this.planeModels;
	}

	public void setPlaneModels(PlaneModels planeModels) {
		this.planeModels = planeModels;
	}

	public PlaneStatus getPlaneStatus() {
		return this.planeStatus;
	}

	public void setPlaneStatus(PlaneStatus planeStatus) {
		this.planeStatus = planeStatus;
	}
}
