/*
 * 
 */
package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

// TODO: Auto-generated Javadoc
/**
 * Routes generated by hbm2java.
 */

@Entity
@Table(name="Routes")
public class Routes implements java.io.Serializable {

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** The airline name. */
	@Transient
	private String airline_name;
	
	/** The id. */
	@Id
	@Column(name="id")
	private int id;
	
	/** The airline id. */
	@Column(name="airline_id")
	private int airline_id;
	
	/** The departure. */
	@Column(name="origin")
	private String departure;
	
	/** The arrival. */
	@Column(name="arrival")
	private String arrival;

	/**
	 * Instantiates a new routes.
	 */
	public Routes() {
	}


	/**
	 * Instantiates a new routes.
	 *
	 * @param id the id
	 * @param airlines the airlines
	 * @param departure the departure
	 * @param arrival the arrival
	 */
	public Routes(int id, int airlines, String departure, String arrival) {
		this.id = id;
		this.airline_id = airlines;
		this.departure = departure;
		this.arrival = arrival;

	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public int getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Gets the airline id.
	 *
	 * @return the airline id
	 */
	public int getAirline_id() {
		return airline_id;
	}


	/**
	 * Sets the airline id.
	 *
	 * @param airline_id the new airline id
	 */
	public void setAirline_id(int airline_id) {
		this.airline_id = airline_id;
	}

	/**
	 * Gets the departure.
	 *
	 * @return the departure
	 */
	public String getDeparture() {
		return this.departure;
	}

	/**
	 * Sets the departure.
	 *
	 * @param departure the new departure
	 */
	public void setDeparture(String departure) {
		this.departure = departure;
	}

	/**
	 * Gets the arrival.
	 *
	 * @return the arrival
	 */
	public String getArrival() {
		return this.arrival;
	}

	/**
	 * Sets the arrival.
	 *
	 * @param arrival the new arrival
	 */
	public void setArrival(String arrival) {
		this.arrival = arrival;
	}


	/**
	 * Gets the airline name.
	 *
	 * @return the airline name
	 */
	public String getAirline_name() {
		return airline_name;
	}


	/**
	 * Sets the airline name.
	 *
	 * @param airline_name the new airline name
	 */
	public void setAirline_name(String airline_name) {
		this.airline_name = airline_name;
	}
	
	
}
