package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Routes generated by hbm2java
 */

@Entity
@Table(name="Routes")
public class Routes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Transient
	private String airline_name;
	
	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="airline_id")
	private int airline_id;
	
	@Column(name="origin")
	private String departure;
	
	@Column(name="arrival")
	private String arrival;

	public Routes() {
	}


	public Routes(int id, int airlines, String departure, String arrival) {
		this.id = id;
		this.airline_id = airlines;
		this.departure = departure;
		this.arrival = arrival;

	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getAirline_id() {
		return airline_id;
	}


	public void setAirline_id(int airline_id) {
		this.airline_id = airline_id;
	}

	public String getDeparture() {
		return this.departure;
	}

	public void setDeparture(String departure) {
		this.departure = departure;
	}

	public String getArrival() {
		return this.arrival;
	}

	public void setArrival(String arrival) {
		this.arrival = arrival;
	}


	public String getAirline_name() {
		return airline_name;
	}


	public void setAirline_name(String airline_name) {
		this.airline_name = airline_name;
	}
	
	
}
