package db_items;
// Generated 04-ene-2017 11:51:08 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tickets generated by hbm2java
 */

@Entity
@Table(name="Tickets")
public class Tickets implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name="id")
	private int id;
	
	@Column(name="flights")
	private Flights flights;
	
	@Column(name="passengers")
	private Passengers passengers;
	
	@Column(name="code")
	private String code;

	public Tickets() {
	}

	public Tickets(int id, Flights flights, Passengers passengers) {
		this.id = id;
		this.flights = flights;
		this.passengers = passengers;
	}

	public Tickets(int id, Flights flights, Passengers passengers, String code) {
		this.id = id;
		this.flights = flights;
		this.passengers = passengers;
		this.code = code;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Flights getFlights() {
		return this.flights;
	}

	public void setFlights(Flights flights) {
		this.flights = flights;
	}

	public Passengers getPassengers() {
		return this.passengers;
	}

	public void setPassengers(Passengers passengers) {
		this.passengers = passengers;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
